# Generated by Django 4.0.5 on 2022-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familymembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People_address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_people', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='people',
            name='address',
        ),
    ]
